### ISSUE TITLE
Account storage capacity overflow 

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-core-contracts#150]
### Issue To Be Solved
The storage fees smart contract overflows when the account balance times the MbPerFlow constant is more than max UFix64. When it overflows it results in the account storage capacity being 0. 

Instead it should result in the account storage capacity being max UFix64.

**This is not a problem for mainnet** as the entire FLOW supply is not high enough.

**Comment by janezpodhostnik** [comment]
@turbolent  can this be done with the current version of cadence?

the function is: (https://github.com/onflow/flow-core-contracts/blob/c327df118949c56787fd0e0980c424733107c2e4/contracts/FlowStorageFees.cdc#L63)

```
    // Returns megabytes
    pub fun calculateAccountCapacity(_ accountAddress: Address): UFix64 {
        let balanceRef = getAccount(accountAddress)
            .getCapability<&FlowToken.Vault{FungibleToken.Balance}>(/public/flowTokenBalance)!
            .borrow() ?? panic("Could not borrow FLOW balance capability")

        // get address token balance
        if balanceRef.balance < self.minimumStorageReservation {
            // if < then minimum return 0
            return 0.0
        } else {
            // return balance multiplied with megabytes per flow 
            return balanceRef.balance * self.storageMegaBytesPerReservedFLOW
        }
    }
```

The last part `balanceRef.balance * self.storageMegaBytesPerReservedFLOW` should return max UFix64 if the multiplication result is more than max UFix64.

**Comment by turbolent** [comment]
I think what we would want is [saturating multiply](https://en.wikipedia.org/wiki/Saturation_arithmetic), that results in the min/max value instead of underflowing/overflow. We don't have that in Cadence, but it could be easily added.

Alternatively, the same behaviour could be implemented by dividing from the max value and checking if the multiplication would result in an overflow. There are currently no max/min constants of number types exposed (e.g. `UFix.max`), but again this could be easily added, and alternatively defined as a constant in the Cadence program itself (e.g. `let UFix64Max = ...`.

I'll create issues for both.
