### ISSUE TITLE
Investigate breaking the staking delegation payout transaction into multiple parts

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-core-contracts#326]
### Problem

The payout transaction resulted in the following [incident](https://www.notion.so/dapperlabs/Flow-block-query-exceeded-max-event-configured-event-size-289f5386ad014164adc4c13711aeb3d5) out of which one fo the action items to explore was how we could break up the transaction into smaller chunks. One suggestion was to all the delegations into bundles, each paying out 1/3 of the overall 

### Acceptance Criteria
* Investigate and determine feasibility of refactoring this single big transaction into smaller ones
* If agreed upon, create tracking GH for the work and add to a sprint backlog

**Comment by dryruner** [comment]
IMO another action to take asap is to turn on automaticRewardsEnabled - https://github.com/onflow/flow-core-contracts/blob/master/contracts/epochs/FlowEpoch.cdc#L369, instead of just performing manual pament

**Comment by joshuahannan** [comment]
As for the events, my proposal is to not emit `DelegatorRewardsPaid` events any more and instead contain the delegator reward information as a new field in the `RewardsPaid` event. This should cut down on the event size a lot because delegator events will not be included which are the vast majority of these events. It will be breaking, but only for those who rely on the delegator events and is an easy fix. I'm going to work on a PR proposal soon to show this
